arch:
    - amd64
language: python
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

jobs:
  include:
  - python: 3.7
    arch: arm64

addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev

before_install:
  - pip install cython
  - python setup.py sdist

install:
  - pip install dist/*.tar.gz

script:
  - cd .. && python -m tables.tests.test_all
  - pt2to3 -h
  - ptrepack -h
  - ptdump -h
  - pttree -h

before_deploy:
  - pip install sphinx sphinx_rtd_theme ipython
  - cd $TRAVIS_BUILD_DIR
  - echo "3.6.1" > VERSION  # WIP remove me
  - cd doc
  - make html
  - touch build/html/.nojekyll
  - echo "www.pytables.org" > build/html/CNAME
  - mkdir build/html/docs  # keep folders in history
  - mkdir build/html/irc  # keep folders in history
  - mkdir build/html/irc/2011  # keep folders in history

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/build/html
  repo: PyTables/pytables.github.com
  target_branch: master
  keep_history: true  # important! keep docs/pdfs that are not part of this repo
  verbose: true
  on:
    branch: master
    python: 3.7
    #tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58f8a9014ef02f6217ec
    on_success: change
