language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

sudo: false

addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev

install:
  - pip install -r requirements.txt
  - pip install cython
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script: make check
